/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `java-library`
    id("com.gradleup.shadow") version "9.4.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven("https://repo.papermc.io/repository/maven-public/") {
        name = "papermc-repo"
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    implementation(libs.com.github.cryptomorin.xseries)
    implementation(libs.org.bstats.bstats.bukkit)
    implementation(libs.folia.scheduler.wrapper)
    compileOnly(libs.com.zaxxer.hikaricp)
    compileOnly(libs.io.papermc.paper.api)
    compileOnly(libs.me.clip.placeholderapi)
    compileOnly(libs.com.google.code.gson.gson)
    compileOnly(libs.com.google.guava.guava)
}

group = "me.mattyhd0"
version = project.extra["pluginVersion"] as String

tasks.build {
    dependsOn(tasks.shadowJar)
}


tasks.shadowJar {
    relocate("com.cryptomorin.xseries", "me.mattyhd0.chatcolor.libs.xseries")
    relocate("org.bstats", "me.mattyhd0.chatcolor.libs.bstats")
    relocate("me.nahu.scheduler", "me.mattyhd0.chatcolor.libs.scheduler")
    exclude("org/slf4j/**")
    archiveFileName.set("ChatColor-Fork-${version}.jar")
}

tasks {
    withType<JavaCompile> {
        options.encoding = "UTF-8"
    }

    withType<Javadoc> {
        options.encoding = "UTF-8"
    }

    processResources {
        val props = mapOf("version" to version)
        inputs.properties(props)
        filesMatching("plugin.yml") {
            expand(props)
        }
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}